server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.php index.html;

    location / {
      try_files $uri $uri.html $uri/ @extensionless-php;
      index index.html index.htm index.php;
    }

    # Reescribe a PHP si existe
    location @php {
        rewrite ^(.+)$ $1.php last;
    }

    # Reescribe a HTML si existe
    location @html {
        rewrite ^(.+)$ $1.html last;
    }

    location ~ \.php$ {
        try_files $uri =404;

        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location @extensionless-php {
      rewrite ^(.*)$ $1.php last;
    }

    error_page 404 /404.php;
}